### PR TITLE
upgrade tone / use getValueAtTime to fix polysynth voicesInUse

### PR DESCRIPTION
**Pull request by therewasaguy**
When I tried this out locally, the polySynth example was monophonic. It was because `voicesInUse.value` returned `0` no matter what.

The reason for that is an annoying issue with Web Audio, where `.value` stops working for audio params after values are scheduled with scheduling methods (i.e. `setValueAtTime`). Anyway, that has been solved in newer versions of Tone.js by using [this getter ](https://github.com/Tonejs/Tone.js/blob/13adf7a3eb39948588760e0bed5e43bf48c42d49/Tone/signal/TimelineSignal.js#L52) for `Tone.TimelineSignal.value` . So, upgrading Tone fixes this. But I also switched from using `.value` to `.getValueAtTime(audioContextTime)` just to be safe, as regular web audio params will still have that problem so we should get in the habit of using `getValueAtTime` all the time.

### CODE REVIEW

**Comment by jvntf** [comment]
sounds like a good idea to use .getValueAtTime-- what were your tests that resulted in the polysynth being monophonic? I seem to be getting polyphony

**Comment by therewasaguy** [comment]
@jvntf I was just using `examples/polyphonicSynth-Keyboard/`

I had Tone 0.6.1 installed (because that is the version currently referenced by `./package.json`). Upgrading to 0.10 fixed it and didn't seem to cause any other issues, so we should upgrade!

What version of Tone do you have? `cat node_modules/tone/package.json | grep version`

**Comment by jvntf** [comment]
ah i had Tone 0.10! good catch, thanks!

**Comment by therewasaguy** [comment]
ah, this makes sense then! Let's definitely update package.json so that we're all on the same version

**Pull request merged**
